# -- SEE helm/transformer/template-transformer FOR A LIST OF ALL AVAILABLE VALUES
# -- NOTE: Additional values MUST be added under the 'mobidp-base-importer-chart' key!
mobidp-base-importer-chart:
  global:
    serviceAccountName: "wrkflw-run-tls-pods-sa"
    imagePullSecrets:
      - name: "mobidrom-registry"
      - name: "ionos-ops-registry-secret"
  importerStep:
    name: "x2gbfs-extractor"
    extractor:
      enabled: true
    image:
      registry: "ghrc.io"
      repository: "mobidrom/x2gbfs"
      name: "x2gbfs-extractor"
      tag: "0.1.0-SNAPSHOT-2604211217"
    allowTrafficTo:
      - "external"
    command: ["/bin/sh", "-c"]
    # args: ["./run_all.sh", "${GBFS_CONFIGS}"]
    args: ["sleep", "3600"]
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 512Mi
    ttlStrategy:
      secondsAfterSuccess: 604800
      secondsAfterFailure: 604800
    volumes:
      extraVolumes:
        - name: out
          emptyDir: {}
          sizeLimit: 100Mi
      extraVolumeMounts:
        - mountPath: /app/out
          name: out
