name: X2GBFS CI

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  application-ci-cd:
    name: Build, Package, Write-Back and Push Updates
    uses: Mobidrom/github-actions/.github/workflows/ci.yaml@main
    secrets: inherit
    with:
      source-repository: "x2gbfs"
      tech-stack: "python"
      tech-stack-version: "3.13"
      image-files: |
        x2gbfs/**
        config/**
        Dockerfile
        run_all.sh
        requirements.txt
        pyproject.toml
      image-parent-directories: "."
      chart-files: charts/**
      chart-files-ignore: |
        charts/**/README.md
      write-back-image-fields: |
        {  "name": ".mobidp-base-importer-chart.importerStep.image.tag", "path": "charts/PATH/values.yaml" },
        {  "name": ".appVersion", "path": "charts/PATH/Chart.yaml" }
      write-back-chart-fields: |
        { "name": ".version", "path": "PATH/Chart.yaml" }
